// scripts/generate-kb-viz.mjs
// Derive the visualization products from the knowledge base:
//   a) src/data/kb-schema-graph.json — type-level schema map (nodes + observed edges)
//   b) kb-graph/                     — Obsidian companion notes (type hubs + one stub per object)
// Both corpora are read: data/kb/ (articles) and kb-handoff/objects/ (handoff; tolerated absent —
// on main the handoff corpus doesn't exist and every output is single-corpus automatically).
// Derived + rebuildable; idempotent: same inputs → byte-identical outputs (no timestamps).
// Run: node scripts/generate-kb-viz.mjs   (or npm run generate:kb-viz)

import {
  readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync, existsSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATED_MARK = 'generated by scripts/generate-kb-viz.mjs';

// Fixed categorical order — the page's palette is assigned by this order (dataviz
// rule: hues in fixed order, never cycled). Unknown types sort after, alphabetically.
export const TYPE_ORDER = [
  'resource', 'source-system', 'concept-lineage', 'claim-evidence',
  'encyclopedia-entry', 'option-entry', 'public-use-boundary',
  'implementation-record', 'signal', 'track',
];
const typeRank = (t) => {
  const i = TYPE_ORDER.indexOf(t);
  return i === -1 ? TYPE_ORDER.length : i;
};

// Codepoint comparator — deterministic across machines/locales. Bare
// `a.localeCompare(b)` uses ICU collation, which varies by platform/locale.
const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

// IDs that exist under more than one type (a real hazard in the merged corpora:
// an id like "giveth" as both a resource and an encyclopedia-entry, say). An
// id→type map can only remember one, so any reference to such an id is
// unattributable — edges/links must skip them rather than silently pick one.
export function findAmbiguousIds(objects) {
  const typesById = new Map();
  for (const o of objects) {
    if (!typesById.has(o.id)) typesById.set(o.id, new Set());
    typesById.get(o.id).add(o.type);
  }
  const ambiguous = new Set();
  for (const [id, types] of typesById) if (types.size > 1) ambiguous.add(id);
  return ambiguous;
}

export function loadArticlesCorpus(kbDir) {
  if (!existsSync(kbDir)) return [];
  const out = [];
  for (const f of readdirSync(kbDir).sort()) {
    if (!f.endsWith('.yaml') || f.startsWith('_')) continue;
    const type = f.replace(/\.yaml$/, '');
    const doc = yaml.load(readFileSync(join(kbDir, f), 'utf8'));
    for (const [id, data] of Object.entries(doc?.entries ?? {})) {
      out.push({ id, type, corpus: 'articles', data: data ?? {} });
    }
  }
  return out;
}

export function loadHandoffCorpus(objDir) {
  if (!existsSync(objDir)) return [];
  const out = [];
  const typeDirs = readdirSync(objDir, { withFileTypes: true })
    .filter((d) => d.isDirectory()).map((d) => d.name).sort();
  for (const type of typeDirs) {
    for (const f of readdirSync(join(objDir, type)).sort()) {
      if (!f.endsWith('.yaml')) continue;
      const id = f.replace(/\.yaml$/, '');
      const data = yaml.load(readFileSync(join(objDir, type, f), 'utf8'));
      out.push({ id, type, corpus: 'handoff', data: data ?? {} });
    }
  }
  return out;
}

// Depth-first over every string value, remembering the nearest field name
// (arrays inherit the array's field name).
function walkValues(node, field, visit) {
  if (node == null) return;
  if (typeof node === 'string') { if (field) visit(field, node); return; }
  if (Array.isArray(node)) { for (const v of node) walkValues(v, field, visit); return; }
  if (typeof node === 'object') {
    for (const [k, v] of Object.entries(node)) walkValues(v, k, visit);
  }
}

// Type→type edges from observed references: a string value that exactly equals
// another object's id, labeled by the field it sat in. Sparse is honest.
// References to an ambiguous id (same id under >1 type) are skipped — the id→type
// map can't attribute them correctly, so a wrong-type edge is worse than no edge.
export function deriveEdges(objects, ambiguous = new Set()) {
  const idToType = new Map(objects.map((o) => [o.id, o.type]));
  const tally = new Map();
  for (const o of objects) {
    walkValues(o.data, null, (field, value) => {
      if (value === o.id || !idToType.has(value) || ambiguous.has(value)) return;
      const key = `${o.type}|${idToType.get(value)}|${field}`;
      tally.set(key, (tally.get(key) ?? 0) + 1);
    });
  }
  return [...tally.entries()]
    .map(([k, count]) => {
      const [from, to, label] = k.split('|');
      return { from, to, label, count };
    })
    .sort((a, b) =>
      typeRank(a.from) - typeRank(b.from) || cmp(a.from, b.from) ||
      typeRank(a.to) - typeRank(b.to) || cmp(a.to, b.to) ||
      cmp(a.label, b.label));
}

export function buildSchemaGraph(objects) {
  const byType = new Map();
  for (const o of objects) {
    if (!byType.has(o.type)) {
      byType.set(o.type, {
        type: o.type, total: 0, raw: 0, reviewed: 0,
        byCorpus: { articles: 0, handoff: 0 },
      });
    }
    const n = byType.get(o.type);
    n.total += 1;
    const m = o.data?.maturity ?? 'raw';
    if (m === 'raw') n.raw += 1;
    if (m === 'reviewed') n.reviewed += 1;
    n.byCorpus[o.corpus] += 1;
  }
  const nodes = [...byType.values()].sort((a, b) =>
    typeRank(a.type) - typeRank(b.type) || cmp(a.type, b.type));
  return { nodes, edges: deriveEdges(objects, findAmbiguousIds(objects)) };
}

export function pickDescription(data) {
  for (const k of ['short_description', 'description', 'summary', 'what_it_curates', 'notes']) {
    if (typeof data?.[k] === 'string' && data[k].trim()) return data[k].trim();
  }
  return '';
}

const safeName = (s) => String(s).replace(/[/\\:#|?*"<>]/g, '-');

export function buildStub(o, idToType, ambiguous = new Set()) {
  const title = (typeof o.data?.title === 'string' && o.data.title.trim()) || o.id;
  const related = new Set();
  walkValues(o.data, null, (_field, value) => {
    if (value !== o.id && idToType.has(value) && !ambiguous.has(value)) related.add(value);
  });
  const rel = [...related].sort(cmp);
  const src = o.corpus === 'articles'
    ? `data/kb/${o.type}.yaml#${o.id}`
    : `kb-handoff/objects/${o.type}/${o.id}.yaml`;
  const fm = yaml.dump({
    kb_type: o.type,
    maturity: o.data?.maturity ?? 'raw',
    corpus: o.corpus,
    ai_assisted: o.data?.ai_assisted ?? false,
  }, { lineWidth: -1 }).trimEnd();
  const desc = pickDescription(o.data);
  return [
    '---', fm, '---', '',
    `# ${title}`, '',
    ...(desc ? [desc, ''] : []),
    `Hub: [[kb-hub-${o.type}]]`,
    ...(rel.length ? ['', `Related: ${rel.map((r) => `[[${safeName(r)}]]`).join(' · ')}`] : []),
    '',
    `Source: \`${src}\``, '',
  ].join('\n');
}

export function main() {
  const objects = [
    ...loadArticlesCorpus(join(ROOT, 'data/kb')),
    ...loadHandoffCorpus(join(ROOT, 'kb-handoff/objects')),
  ];
  const { nodes, edges } = buildSchemaGraph(objects);
  const corpora = {
    articles: objects.filter((o) => o.corpus === 'articles').length,
    handoff: objects.filter((o) => o.corpus === 'handoff').length,
  };
  const ambiguous = findAmbiguousIds(objects);
  if (ambiguous.size) {
    console.warn(`kb-viz: ${ambiguous.size} ambiguous ids skipped for edges/links: ${[...ambiguous].sort(cmp).join(', ')}`);
  }

  // a) The schema-map JSON for the site.
  writeFileSync(join(ROOT, 'src/data/kb-schema-graph.json'), JSON.stringify({
    generated_from: 'derived — rebuildable via npm run generate:kb-viz',
    corpora, nodes, edges,
  }, null, 2) + '\n');

  // b) kb-graph/ Obsidian companion notes.
  // Vault safety: refuse to clear a kb-graph/ this script didn't generate.
  const kbGraph = join(ROOT, 'kb-graph');
  const readmePath = join(kbGraph, 'README.md');
  if (existsSync(kbGraph)) {
    if (!existsSync(readmePath) || !readFileSync(readmePath, 'utf8').includes(GENERATED_MARK)) {
      throw new Error('kb-graph/ exists but has no generated marker — refusing to overwrite. Move it aside first.');
    }
    rmSync(kbGraph, { recursive: true });
  }
  mkdirSync(join(kbGraph, 'hubs'), { recursive: true });

  const idToType = new Map(objects.map((o) => [o.id, o.type]));
  const byType = new Map(nodes.map((n) => [n.type, []]));
  for (const o of objects) byType.get(o.type).push(o);

  for (const [type, members] of byType) {
    mkdirSync(join(kbGraph, type), { recursive: true });
    members.sort((a, b) => cmp(a.id, b.id));
    for (const o of members) {
      writeFileSync(join(kbGraph, type, `${safeName(o.id)}.md`), buildStub(o, idToType, ambiguous));
    }
    const n = nodes.find((x) => x.type === type);
    writeFileSync(join(kbGraph, 'hubs', `kb-hub-${type}.md`), [
      '---', `kb_hub: ${type}`, '---', '',
      `# ${type} — ${n.total} objects`, '',
      `${n.raw} raw · ${n.reviewed} reviewed · articles ${n.byCorpus.articles} / handoff ${n.byCorpus.handoff}`, '',
      `Up: [[kb-commons]]`, '',
      ...members.map((o) => {
        const title = (typeof o.data?.title === 'string' && o.data.title.trim()) || o.id;
        return `- [[${safeName(o.id)}|${title.replace(/[|[\]]/g, ' ').trim()}]]`;
      }),
      '',
    ].join('\n'));
  }

  writeFileSync(join(kbGraph, 'kb-commons.md'), [
    '---', 'kb_hub: root', '---', '',
    '# Knowledge Commons', '',
    `${objects.length} objects · ${nodes.length} types · corpora: articles ${corpora.articles} / handoff ${corpora.handoff}`, '',
    ...nodes.map((n) => `- [[kb-hub-${n.type}|${n.type}]] — ${n.total} (${n.raw} raw · ${n.reviewed} reviewed)`),
    '',
  ].join('\n'));

  writeFileSync(readmePath, [
    `# kb-graph/ — Obsidian companion notes (${GENERATED_MARK})`, '',
    'Derived, rebuildable renderings of the knowledge base for Obsidian graph view.',
    'Do not edit by hand — regenerate with `npm run generate:kb-viz`.',
    'Entry point: [[kb-commons]]. One stub per KB object; hubs cluster the graph by type.', '',
  ].join('\n'));

  console.log(`kb-viz: ${nodes.length} types · ${objects.length} objects · ${edges.length} edges → src/data/kb-schema-graph.json + kb-graph/`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
